version: '3.7'
services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
            http.cors.enabled: "true"
            http.cors.allow-origin: "https://app.elasticvue.com"
        ports:
            - "9200:9200"
